# Generated by Django 5.2.4 on 2025-08-11 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments_and_comments', '0001_initial'),
        ('projectmanagement', '0004_alter_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projectmanagement.taskmodel'),
        ),
    ]
