# Generated by Django 5.2.4 on 2025-08-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments_and_comments', '0002_alter_comments_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
    ]
