# Generated by Django 5.2.4 on 2025-08-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querrypractice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', to='querrypractice.doctormodel'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='querrypractice.nursemodel'),
        ),
    ]
