# Generated by Django 5.2.4 on 2025-08-15 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querrypractice', '0002_alter_patientmodel_doctors_alter_patientmodel_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='querrypractice.patientmodel'),
        ),
    ]
