# Generated by Django 5.2.4 on 2025-08-19 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querrypractice', '0003_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='doctors',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='doctors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='querrypractice.doctormodel'),
        ),
    ]
