# Generated by Django 5.2.5 on 2025-08-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querrypractice', '0004_notificationmodel_remove_patientmodel_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nursemodel',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nursemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
