# Generated by Django 5.2.5 on 2025-08-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querrypractice', '0005_alter_doctormodel_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='doctors',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', to='querrypractice.doctormodel'),
        ),
    ]
