# Generated by Django 5.2.5 on 2025-08-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querrypractice', '0006_remove_patientmodel_doctors_patientmodel_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='contact_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
