# Generated by Django 5.2.4 on 2025-08-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querrypractice', '0007_alter_doctormodel_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='doctors',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='querrypractice.doctormodel'),
        ),
    ]
