# Generated by Django 5.2.4 on 2025-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querrypractice', '0008_remove_patientmodel_doctors_patientmodel_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='message',
            field=models.CharField(max_length=150),
        ),
    ]
