# Generated by Django 5.2.4 on 2025-08-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_projectmodel_status_alter_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('working', 'Working'), ('review', 'Review'), ('waiting_qa', 'Waiting QA'), ('awaiting_release', 'Awaiting Release'), ('closed', 'Closed')], default='open', max_length=30),
        ),
    ]
